sudo: required
services:
  - docker
before_install:
  - docker build -t sangeetha/gitproject -f Dockerfile.dev .
script:
  - docker run -e CI=true sangeetha/gitproject npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name:"elasticbeanstalk-us-east-2-127010575588"
  bucket_path:"docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
